name: chronomap_mobile
description: "mobile app for global chronomap"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+4

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  serverpod_flutter: ^2.0.0
  acorn_client:
    git:
      url: https://github.com/dongri727/acorn.git
      path: acorn_client

  intl: ^0.18.1
  provider: ^6.0.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.5

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_native_splash:
  color: '#111124'
  image: 'assets/images/splash_768.png'
  color_dark: '#111124'
  image_dark: 'assets/images/splash_768.png'
  fullscreen: true
  android_12:
    icon_background_color: '#111124'
    image: 'assets/images/splash_1152.png'
    icon_background_color_dark: '#111124'
    image_dark: 'assets/images/splash_1152.png'

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon.png'
  adaptive_icon_background: '#111124'
  adaptive_icon_foreground: 'assets/images/icon_adaptive.png'

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/splash_1152.png
    - assets/images/splash_768.png
    - assets/images/icon.png
    - assets/images/icon_adaptive.png
    - assets/images/cover_en.png
    - assets/images/cover_fr.png
    - assets/images/cover_ja.png

